# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:
- task: octane-start-task@2
  inputs:
    OctaneServiceConnection: 'ALMOctane'
    WorkspaceList: '1039'
- task: octane-start-task-private@1
  condition: always()
  inputs:
    OctaneServiceConnection: 'ALMOctane'
    WorkspaceList: '1039'
    CreatePipelineCheckbox: true
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Maven@4
  continueOnError: true
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: octane-end-task@2
  inputs:
    OctaneServiceConnection: 'ALMOctane'
    WorkspaceList: '1039'
    # Starter pipeline
    - task: octane-end-task-private@1
    condition: always()
      inputs:
        OctaneServiceConnection: 'ALMOctane'
        WorkspaceList: '1039'
        CreatePipelineCheckbox: true